
services:
  backend:
    build: ./backend
    container_name: tallshipraces_backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL = "mongodb+srv://admin:admin12@tallshipraces.9aydfnp.mongodb.net/admin?retryWrites=true&w=majority"

  frontend:
    build: ./frontend
    container_name: tallshipraces_frontend
    ports:
      - "3000:80"  # nginx serves on port 80

  mongo:
    image: mongo:latest
    container_name: tallshipraces_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
