
services:
  backend:
    build: ./backend
    container_name: eventconnect_backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017

  frontend:
    build: ./frontend
    container_name: eventconnect_frontend
    ports:
      - "3000:80"  # nginx serves on port 80

  mongo:
    image: mongo:latest
    container_name: eventconnect_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
